# Generated by Django 2.1.5 on 2019-02-13 18:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('price_current', models.FloatField()),
                ('price_desired', models.FloatField()),
                ('price_currency', models.CharField(max_length=5)),
                ('product_url', models.URLField(max_length=500)),
                ('last_checked_date', models.DateTimeField(default=datetime.datetime(2019, 2, 13, 18, 34, 5, 486259, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
