# Generated by Django 2.1.5 on 2019-02-13 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracked_prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedprice',
            name='last_checked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
