# Generated by Django 2.1.5 on 2019-03-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracked_prices', '0004_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedprice',
            name='when_inform',
            field=models.CharField(choices=[('A', 'Gdy cena osiągnie konkretny poziom'), ('B', 'Gdy cena spadnie o x procent')], default='A', max_length=1),
        ),
    ]
