# Generated by Django 2.1.5 on 2019-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracked_prices', '0008_auto_20190316_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedprice',
            name='when_inform',
            field=models.CharField(choices=[('A', 'Gdy cena spadnie'), ('B', 'Gdy cena spadnie o x procent'), ('C', 'Gdy cena osiągnie pożądaną wartość')], default='A', max_length=1),
        ),
    ]
