# Generated by Django 2.1.5 on 2019-03-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracked_prices', '0009_auto_20190317_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedprice',
            name='desired',
            field=models.FloatField(default=1),
        ),
    ]
