# Generated by Django 2.1.5 on 2019-02-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracked_prices', '0002_auto_20190213_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackedprice',
            old_name='price_currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='trackedprice',
            old_name='price_current',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='trackedprice',
            old_name='price_desired',
            new_name='desired',
        ),
        migrations.RenameField(
            model_name='trackedprice',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trackedprice',
            old_name='product_url',
            new_name='url',
        ),
    ]
