# Generated by Django 2.1.5 on 2019-03-16 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracked_prices', '0005_trackedprice_when_inform'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedprice',
            name='percent_drop',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
