# Generated by Django 2.1.5 on 2019-03-16 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracked_prices', '0007_auto_20190316_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedprice',
            name='percent_drop',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
